### PR TITLE
new release ckan-2.9.11 & ckan-2.10.4

### PR DESCRIPTION
**Pull request by stojanovskis1**

### CODE REVIEW

**Comment by KirilPoposki98** [comment]
Change image versions in docker compose also

**Comment by stojanovskis1** [comment]
Changed tag in compose and also in examples

**Comment by KirilPoposki98** [comment]
I tested 2.10.4 and is working properly. Can someone do the same for 2.9.11 ?

**Review by KirilPoposki98 — APPROVED** [review]
Tested 2.10.4

**Review by Filip3mac — APPROVED** [review]

**Pull request merged**
